const a11 = [
   { id: "a11-1", de: "ansehen", article: "", ru: "смотреть" },
   { id: "a11-2", de: "Bild", article: "das", ru: "картина" },
   { id: "a11-3", de: "hören", article: "", ru: "слышать" },
   { id: "a11-4", de: "noch einmal", article: "", ru: "еще раз" },
   { id: "a11-5", de: "ankreuzen", article: "", ru: "отмечать галочкой" },
   { id: "a11-6", de: "zuordnen", article: "", ru: "сопоставлять" },
   { id: "a11-7", de: "ergänzen", article: "", ru: "дополнять" },
   { id: "a11-8", de: "machen", article: "", ru: "делать" },
   { id: "a11-9", de: "Kurs", article: "der", ru: "курс" },
   { id: "a11-10", de: "sprechen", article: "", ru: "говорить" },
   { id: "a11-11", de: "lesen", article: "", ru: "читать" },
   { id: "a11-12", de: "Gespräch", article: "das", ru: "разговор" },
   { id: "a11-13", de: "spielen", article: "", ru: "играть" },
   { id: "a11-14", de: "suchen", article: "", ru: "искать" },
   { id: "a11-15", de: "zeigen", article: "", ru: "показывать" },
   { id: "a11-16", de: "fragen", article: "", ru: "спрашивать" },
   { id: "a11-17", de: "markieren", article: "", ru: "выделять" },
   { id: "a11-18", de: "Frage", article: "die", ru: "вопрос" },
   { id: "a11-19", de: "nachsprechen", article: "", ru: "повторять" },
   { id: "a11-20", de: "raten", article: "", ru: "угадывать" },
   { id: "a11-21", de: "Wort", article: "das", ru: "слово" },
   { id: "a11-22", de: "Lektion", article: "die", ru: "урок" },
   { id: "a11-23", de: "meinen", article: "", ru: "думать" },
   { id: "a11-24", de: "sagen", article: "", ru: "говорить" },
   { id: "a11-25", de: "notieren", article: "", ru: "записывать" },
   { id: "a11-26", de: "vergleichen", article: "", ru: "сравнивать" },
   { id: "a11-27", de: "schreiben", article: "", ru: "писать" },
   { id: "a11-28", de: "variieren", article: "", ru: "варьировать" },
   { id: "a11-29", de: "erzählen", article: "", ru: "рассказывать" },
   { id: "a11-30", de: "arbeiten", article: "", ru: "работать" },
   { id: "a11-31", de: "zeichnen", article: "", ru: "рисовать" },
   { id: "a11-32", de: "verbinden", article: "", ru: "соединять" },
   { id: "a11-33", de: "Antwort", article: "die", ru: "ответ" },
   { id: "a11-34", de: "ich", article: "", ru: "я" },
   { id: "a11-35", de: "heißen", article: "", ru: "называться" },
   { id: "a11-36", de: "Name", article: "der", ru: "имя" },
   { id: "a11-37", de: "kommen", article: "", ru: "приходить" },
   { id: "a11-38", de: "Deutschland", article: "", ru: "Германия" },
   { id: "a11-39", de: "sprechen", article: "", ru: "говорить" },
   { id: "a11-40", de: "Deutsch", article: "das", ru: "немецкий язык" },
   { id: "a11-41", de: "und", article: "", ru: "и" },
   { id: "a11-42", de: "ein bisschen", article: "", ru: "немного" },
   { id: "a11-43", de: "Guten Tag", article: "", ru: "Добрый день" },
   { id: "a11-44", de: "hallo", article: "", ru: "привет" },
   { id: "a11-45", de: "Auf Wiedersehen", article: "", ru: "До свидания" },
   { id: "a11-46", de: "tschüs", article: "", ru: "пока" },
   { id: "a11-47", de: "Herr", article: "der", ru: "господин" },
   { id: "a11-48", de: "Kind", article: "das", ru: "ребенок" },
   { id: "a11-49", de: "Guten Abend", article: "", ru: "Добрый вечер" },
   { id: "a11-50", de: "Dame", article: "die", ru: "дама" },
   { id: "a11-51", de: "willkommen", article: "", ru: "добро пожаловать" },
   { id: "a11-52", de: "bei", article: "", ru: "у" },
   { id: "a11-53", de: "Musik", article: "die", ru: "музыка" },
   { id: "a11-54", de: "international", article: "", ru: "международный" },
   { id: "a11-55", de: "Guten Morgen", article: "", ru: "Доброе утро" },
   { id: "a11-56", de: "Frau", article: "die", ru: "женщина" },
   { id: "a11-57", de: "danke", article: "", ru: "спасибо" },
   { id: "a11-58", de: "Gute Nacht", article: "", ru: "Спокойной ночи" },
   { id: "a11-59", de: "Papa", article: "der", ru: "папа" },
   { id: "a11-60", de: "sein", article: "", ru: "быть" },
   { id: "a11-61", de: "Entschuldigung", article: "die", ru: "извинение" },
   { id: "a11-62", de: "wie", article: "", ru: "как" },
   { id: "a11-63", de: "Sie", article: "", ru: "Вы" },
   { id: "a11-64", de: "wer", article: "", ru: "кто" },
   { id: "a11-65", de: "ja", article: "", ru: "да" },
   { id: "a11-66", de: "nein", article: "", ru: "нет" },
   { id: "a11-67", de: "woher", article: "", ru: "откуда" },
   { id: "a11-68", de: "aus", article: "", ru: "из" },
   { id: "a11-69", de: "du", article: "", ru: "ты" },
   { id: "a11-70", de: "Österreich", article: "", ru: "Австрия" },
   { id: "a11-71", de: "Schweiz", article: "die", ru: "Швейцария" },
   { id: "a11-72", de: "toll", article: "", ru: "отлично" },
   { id: "a11-73", de: "interessant", article: "", ru: "интересно" },
   { id: "a11-74", de: "was", article: "", ru: "что" },
   { id: "a11-75", de: "auch", article: "", ru: "тоже" },
   { id: "a11-76", de: "Sprache", article: "die", ru: "язык" },
   { id: "a11-77", de: "Buchstabe", article: "der", ru: "буква" },
   { id: "a11-78", de: "Alphabet", article: "das", ru: "алфавит" },
   { id: "a11-79", de: "wie", article: "", ru: "как" },
   { id: "a11-80", de: "buchstabieren", article: "", ru: "продиктовать по буквам" },
   { id: "a11-81", de: "bitte", article: "", ru: "пожалуйста" },
   { id: "a11-82", de: "Firma", article: "die", ru: "компания" },
   { id: "a11-83", de: "vielen Dank", article: "", ru: "большое спасибо" },
   { id: "a11-84", de: "auf Wiederhören", article: "", ru: "до свидания" },
   { id: "a11-85", de: "Adresse", article: "die", ru: "адрес" },
   { id: "a11-86", de: "Visitenkarte", article: "die", ru: "визитная карточка" },
   { id: "a11-87", de: "Vorname", article: "der", ru: "имя" },
   { id: "a11-88", de: "Familienname", article: "der", ru: "фамилия" },
   { id: "a11-89", de: "Straße", article: "die", ru: "улица" },
   { id: "a11-90", de: "Stadt", article: "die", ru: "город" },
   { id: "a11-91", de: "Land", article: "das", ru: "страна" },
   { id: "a11-92", de: "E-Mail", article: "die", ru: "электронная почта" },
   { id: "a11-93", de: "Telefon", article: "das", ru: "телефон" },
   { id: "a11-94", de: "Formular", article: "das", ru: "форма" },
   { id: "a11-95", de: "Kurs", article: "der", ru: "курс" },
   { id: "a11-96", de: "Fremdsprache", article: "die", ru: "иностранный язык" },
   { id: "a11-97", de: "Anmeldung", article: "die", ru: "регистрация" },
   { id: "a11-98", de: "Postleitzahl", article: "die", ru: "индекс" },
   { id: "a11-99", de: "lernen", article: "", ru: "учиться" },
   { id: "a11-100", de: "Park", article: "der", ru: "парк" },
   { id: "a11-101", de: "Pause", article: "die", ru: "перерыв" },
   { id: "a11-102", de: "Familie", article: "die", ru: "семья" },
   { id: "a11-103", de: "Vater", article: "der", ru: "отец" },
   { id: "a11-104", de: "Großeltern", article: "die", ru: "дедушка и бабушка" },
   { id: "a11-105", de: "Mutter", article: "die", ru: "мать" },
   { id: "a11-106", de: "Eltern", article: "die", ru: "родители" },
   { id: "a11-107", de: "Bruder", article: "der", ru: "брат" },
   { id: "a11-108", de: "Geschwister", article: "die", ru: "братья и сестры" },
   { id: "a11-109", de: "Jahr", article: "das", ru: "год" },
   { id: "a11-110", de: "leben", article: "", ru: "жить" },
   { id: "a11-111", de: "in", article: "", ru: "в" },
   { id: "a11-112", de: "gut", article: "", ru: "хорошо" },
   { id: "a11-113", de: "super", article: "", ru: "отлично" },
   { id: "a11-114", de: "na ja", article: "", ru: "так себе" },
   { id: "a11-115", de: "so", article: "", ru: "так" },
   { id: "a11-116", de: "sehr", article: "", ru: "очень" },
   { id: "a11-117", de: "Enkel", article: "der", ru: "внук" },
   { id: "a11-118", de: "Enkelin", article: "die", ru: "внучка" },
   { id: "a11-119", de: "Tochter", article: "die", ru: "дочь" },
   { id: "a11-120", de: "Sohn", article: "der", ru: "сын" },
   { id: "a11-121", de: "Schwester", article: "die", ru: "сестра" },
   { id: "a11-122", de: "Oma", article: "die", ru: "бабушка" },
   { id: "a11-123", de: "Opa", article: "der", ru: "дедушка" },
   { id: "a11-124", de: "Mann", article: "der", ru: "мужчина" },
   { id: "a11-125", de: "dein", article: "", ru: "твой" },
   { id: "a11-126", de: "mein", article: "", ru: "мой" },
   { id: "a11-127", de: "ihr", article: "", ru: "ваш" },
   { id: "a11-128", de: "Ehemann", article: "der", ru: "муж" },
   { id: "a11-129", de: "Ehefrau", article: "die", ru: "жена" },
   { id: "a11-130", de: "falsch", article: "", ru: "неправильно" },
   { id: "a11-131", de: "singular", article: "", ru: "единственное число" },
   { id: "a11-132", de: "plural", article: "", ru: "множественное число" },
   { id: "a11-133", de: "sie (Singular)", article: "", ru: "она (единственное число)" },
   { id: "a11-134", de: "sie (Plural)", article: "", ru: "они (множественное число)" },
   { id: "a11-135", de: "zusammen", article: "", ru: "вместе" },
   { id: "a11-136", de: "geschieden", article: "", ru: "разведен" },
   { id: "a11-137", de: "er", article: "", ru: "он" },
   { id: "a11-138", de: "wohnen", article: "", ru: "жить" },
   { id: "a11-139", de: "jetzt", article: "", ru: "сейчас" },
   { id: "a11-140", de: "wir", article: "", ru: "мы" },
   { id: "a11-141", de: "Zahl", article: "die", ru: "число" },
   { id: "a11-142", de: "wo", article: "", ru: "где" },
   { id: "a11-143", de: "geboren", article: "", ru: "родился" },
   { id: "a11-144", de: "Nummer", article: "die", ru: "номер" },
   { id: "a11-145", de: "verheiratet", article: "", ru: "женат" },
   { id: "a11-146", de: "haben", article: "", ru: "иметь" },
   { id: "a11-147", de: "Geburtsort", article: "der", ru: "место рождения" },
   { id: "a11-148", de: "Wohnort", article: "der", ru: "место жительства" },
   { id: "a11-149", de: "Familienstand", article: "der", ru: "семейное положение" },
   { id: "a11-150", de: "ledig", article: "", ru: "холост" },
   { id: "a11-151", de: "verwitwet", article: "", ru: "вдовец" },
   { id: "a11-152", de: "Alter", article: "das", ru: "возраст" },
   { id: "a11-153", de: "Norden", article: "der", ru: "север" },
   { id: "a11-154", de: "Süden", article: "der", ru: "юг" },
   { id: "a11-155", de: "Westen", article: "der", ru: "запад" },
   { id: "a11-156", de: "Osten", article: "der", ru: "восток" },
   { id: "a11-157", de: "Hauptstadt", article: "die", ru: "столица" }
];

const a12 = [
   { id: 'a12-1', de: 'Baum', article: 'der', ru: 'дерево' },
   { id: 'a12-2', de: 'Blume', article: 'die', ru: 'цветок' },
   { id: 'a12-3', de: 'Gras', article: 'das', ru: 'трава' },
   { id: 'a12-4', de: 'Fisch', article: 'der', ru: 'рыба' }
];

const a21 = [
   { id: 'a21-1', de: 'Blatt', article: 'das', ru: 'лист' },
   { id: 'a21-2', de: 'Tier', article: 'das', ru: 'животное' },
   { id: 'a21-3', de: 'Vogel', article: 'der', ru: 'птица' },
   { id: 'a21-4', de: 'Ente', article: 'die', ru: 'утка' }
]

const a22 = [
   { id: 'a22-1', de: 'Pferd', article: 'das', ru: 'лошадь' },
   { id: 'a22-2', de: 'Elefant', article: 'der', ru: 'слон' },
   { id: 'a22-3', de: 'Giraffe', article: 'die', ru: 'жираф' },
   { id: 'a22-4', de: 'Löwe', article: 'der', ru: 'лев' },
]

const b11 = [
   { id: 'b11-1', de: 'Eichhörnchen', article: 'das', ru: 'белка' },
   { id: 'b11-2', de: 'Eule', article: 'die', ru: 'сова' },
   { id: 'b11-3', de: 'Frosch', article: 'der', ru: 'лягушка' },
   { id: 'b11-4', de: 'Schwein', article: 'das', ru: 'свинья' }
]

const b12 = [
   { id: 'b12-1', de: 'Kuh', article: 'die', ru: 'корова' },
   { id: 'b12-2', de: 'Schaf', article: 'das', ru: 'овца' },
   { id: 'b12-3', de: "Hase", article: "der", ru: "заяц" },
   { id: 'b12-4', de: "Bär", article: "der", ru: "медведь" }
]

export const allWords = a11.concat(a12);
export const modules = [
   { name: 'Все', module: allWords },
   { name: 'A1.1', module: a11 },
   { name: 'A1.2', module: a12 },
   { name: 'A2.1', module: a21 },
   { name: 'A2.2', module: a22 },
   { name: 'B1.1', module: b11 },
   { name: 'B1.2', module: b12 }
]
